#!/usr/bin/python3
# A script template week 2
# Licensed under the MIT License (https://opensource.org/license/mit)
# ARI-20130930

# Set up initial variables and imports
import sys

# Script/Library Functions
def calculate_average(numbers):
    """Cal the avg of a list of #s to two decimal places."""

def main():
    if len(sys.argv) != 6:
        print("Usage: ./avg5.py num1 num2 num3 num4 num5")
        print("All inputs must be positive numbers.")
        sys.exit(1)
    

# Run main() if script called directly, else use as a library to be imported
if __name__ == '__main__':
    main()
